// Generate Weekly Top 10 content from real data
// Run: npx tsx --env-file=.env scripts/weekly-content.ts
// Outputs Markdown ready for Dev.to / Reddit

import { db } from "../src/db/index.js";
import { servers, tools, qualityScores, feedback } from "../src/db/schema.js";
import { desc, eq, sql } from "drizzle-orm";

async function generate() {
  // Top tools by quality score
  const top = await db
    .select({
      toolName: tools.name,
      serverName: servers.name,
      grade: qualityScores.grade,
      score: qualityScores.overallScore,
      description: tools.description,
      metadata: servers.metadata,
      publisher: servers.publisher,
    })
    .from(tools)
    .innerJoin(servers, eq(tools.serverId, servers.id))
    .innerJoin(qualityScores, eq(tools.id, qualityScores.toolId))
    .orderBy(desc(qualityScores.overallScore))
    .limit(20);

  // Stats
  const [serverCount, toolCount, fbCount] = await Promise.all([
    db.select({ count: sql<number>`count(*)` }).from(servers),
    db.select({ count: sql<number>`count(*)` }).from(tools),
    db.select({ count: sql<number>`count(*)` }).from(feedback),
  ]);

  const total = Number(serverCount[0]?.count ?? 0);
  const toolsTotal = Number(toolCount[0]?.count ?? 0);
  const feedbackTotal = Number(fbCount[0]?.count ?? 0);

  const week = new Date().toISOString().slice(0, 10);
  const landingUrl = "https://agent-tool-intel-production.up.railway.app";

  console.log(`# Top MCP Tools — Week of ${week}\n`);
  console.log(`*Curated by [Agent Tool Intel](${landingUrl}) — quality scores for ${total.toLocaleString()} MCP servers.*\n`);
  console.log(`---\n`);
  console.log(`## 🔥 Featured This Week\n`);

  // Top 3
  for (let i = 0; i < 3 && i < top.length; i++) {
    const t = top[i]!;
    const stars = (t.metadata as any)?.github_stars || 0;
    const encoded = encodeURIComponent(t.serverName);
    const badgeUrl = `${landingUrl}/badge/${encoded}`;
    const healthUrl = `${landingUrl}/health/${t.serverName}`;

    console.log(`### ${t.toolName} by ${t.publisher || t.serverName.split("/")[0]}`);
    console.log(`![Grade ${t.grade}](${badgeUrl})`);
    console.log(`- **Grade:** ${t.grade} (${t.score}/100)`);
    console.log(`- **What it does:** ${(t.description || "").slice(0, 120)}`);
    console.log(`- **Stars:** ${stars.toLocaleString()}`);
    console.log(`- **Full Report:** ${healthUrl}`);
    console.log();
  }

  console.log(`---\n`);
  console.log(`## 💎 Hidden Gems (High quality, under 50 stars)\n`);
  const hidden = top.filter(t => ((t.metadata as any)?.github_stars || 0) < 50 && ((t.metadata as any)?.github_stars || 0) > 0).slice(0, 3);
  for (const t of hidden) {
    const stars = (t.metadata as any)?.github_stars || 0;
    console.log(`- **${t.serverName}** — Grade ${t.grade} (${t.score}) · ⭐ ${stars} · ${(t.description || "").slice(0, 80)}`);
  }

  console.log(`\n---\n`);
  console.log(`## 📊 Platform Stats\n`);
  console.log(`- **${total.toLocaleString()}** MCP servers indexed`);
  console.log(`- **${toolsTotal.toLocaleString()}** tools scored`);
  console.log(`- **${feedbackTotal.toLocaleString()}** agent feedback events`);

  console.log(`\n---\n`);
  console.log(`*Generated by Agent Tool Intel. [Check your tool's grade](${landingUrl}) · [Methodology](${landingUrl}/scoring/methodology) · [GitHub](https://github.com/HMCHENGGH/agent-tool-intel)*`);
}

generate().catch(console.error);
